# Generated by Django 2.2.3 on 2019-07-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.IntegerField()),
                ('location', models.CharField(max_length=250)),
                ('projector_status', models.BooleanField(default=True)),
                ('comm_status', models.BooleanField(default=True)),
            ],
        ),
    ]
