# Generated by Django 2.2.3 on 2019-07-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominfo',
            name='name',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
